# Generated by Django 4.1.1 on 2022-10-07 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0003_alter_uzsakymoeilute_uzsakymas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automobilis',
            options={'ordering': ['-id'], 'verbose_name': 'Automobilis', 'verbose_name_plural': 'Automobiliai'},
        ),
        migrations.AlterModelOptions(
            name='uzsakymas',
            options={'ordering': ['-id'], 'verbose_name': 'Užsakymas', 'verbose_name_plural': 'Užsakymai'},
        ),
        migrations.AddField(
            model_name='automobilis',
            name='photo',
            field=models.ImageField(null=True, upload_to='automobiliai', verbose_name='Nuotrauka'),
        ),
        migrations.AlterField(
            model_name='uzsakymas',
            name='automobilis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uzsakymai', to='autoservice.automobilis'),
        ),
    ]