# Generated by Django 4.1.1 on 2022-10-11 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autoservice', '0004_alter_automobilis_options_alter_uzsakymas_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzsakymas',
            name='terminas',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Terminas'),
        ),
        migrations.AddField(
            model_name='uzsakymas',
            name='vartotojas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uzsakymas',
            name='data',
            field=models.DateField(auto_now_add=True, verbose_name='Data'),
        ),
    ]